remote_theme: broccolini/swiss
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: WiSCA – Women in Software & Computing Canada
description: Join us in rebuilding community and continuing the mission of empowering diverse women to excel in technology careers.
